// Auto-generated by Claude 3.5 Haiku via Docker Pipeline
// Logo Integration Component for Disaster Recovery Platform
// Generated: 2025-08-31 11:26:31

import React from 'react';
import Image from 'next/image';
import { cn } from '@/lib/utils';

interface LogoProps {
  variant?: 'disaster-recovery' | 'nrp' | 'combined';
  size?: 'sm' | 'md' | 'lg' | 'xl';
  className?: string;
  showText?: boolean;
  darkMode?: boolean;
}

/**
 * Unified Logo Component
 * Replaces all shield and square placeholder logos throughout the site
 */
export const Logo: React.FC<LogoProps> = ({
  variant = 'disaster-recovery',
  size = 'md',
  className,
  showText = true,
  darkMode = false }) => {
  // Size mappings
  const sizeConfig = {
    sm: { width: 32, height: 32, textSize: 'text-sm' },
    md: { width: 48, height: 48, textSize: 'text-base' },
    lg: { width: 64, height: 64, textSize: 'text-lg' },
    xl: { width: 96, height: 96, textSize: 'text-xl' } };

  const config = sizeConfig[size];

  // Logo paths using compressed images
  const logoSources = {
    'disaster-recovery': '/logos/3D Disaster Recovery Logo Image.png',
    'nrp': '/logos/3D NRP Logo.png',
    'combined': '/logos/3D Disaster Recovery Logo Image.png' };

  const logoAltText = {
    'disaster-recovery': 'Disaster Recovery',
    'nrp': 'NRP',
    'combined': 'Disaster Recovery by NRP' };

  return (
    <div className={cn('flex items-center gap-2', className)}>
      <div className="relative">
        <Image
          src={logoSources[variant]}
          alt={logoAltText[variant]}
          width={config.width}
          height={config.height}
          className={cn(
            'object-contain',
            darkMode && 'brightness-0 invert'
          )}
          priority
        />
      </div>
      
      {showText && (
        <div className={cn('flex flex-col', config.textSize)}>
          <span className={cn(
            'font-bold',
            darkMode ? 'text-white' : 'text-gray-900'
          )}>
            {variant === 'nrp' ? 'NRP' : 'Disaster Recovery'}
          </span>
          {variant === 'combined' && (
            <span className={cn(
              'text-xs',
              darkMode ? 'text-gray-300' : 'text-gray-200'
            )}>
              Powered by NRP
            </span>
          )}
        </div>
      )}
    </div>
  );
};

/**
 * Header Logo Component
 * Specifically for use in the site header/navbar
 */
export const HeaderLogo: React.FC<{ darkMode?: boolean }> = ({ darkMode }) => {
  return (
    <Logo
      variant="disaster-recovery"
      size="md"
      showText={false}
      darkMode={darkMode}
      className="cursor-pointer hover:opacity-90 transition-opacity"
    />
  );
};

/**
 * Footer Logo Component
 * Shows both logos in the footer
 */
export const FooterLogos: React.FC<{ darkMode?: boolean }> = ({ darkMode }) => {
  return (
    <div className="flex items-center gap-8">
      <Logo
        variant="disaster-recovery"
        size="lg"
        showText={true}
        darkMode={darkMode}
      />
      <div className="h-12 w-px bg-gray-300 dark:bg-gray-600" />
      <Logo
        variant="nrp"
        size="lg"
        showText={true}
        darkMode={darkMode}
      />
    </div>
  );
};

// Export a hook for dynamic logo usage
export const useLogos = () => {
  const logos = {
    disasterRecovery: '/logos/3D Disaster Recovery Logo Image.png',
    nrp: '/logos/3D NRP Logo.png',
    cleanClaims: '/logos/3D Clean Claims.png',
    carsi: '/logos/3D CARSI Logo.png',
    combined: '/logos/3D Disaster Recovery Logo Image.png' };

  return logos;
};

export default Logo;
